
echo '                  `/dMNdNMMNNhNNdNNdNmdmmmNdNNhmmyNmhmdhmhmNdNNdNNdNMMMm-                 '
echo '                .sNMmmmNMMMNNdNmdmNMNmmmmmmdmmdNmdMMMddhdhhdhdddNNNmmdMMNh:               '
echo '              `sNMNhMMmhyMMmmNdmNdNMMMNdNNdNNdNNmNNMNNMNhNNymdymddNMNNdNMNMh:     `..-..  '
echo '            `+NMdmmMN+:-hMdmmdmNdmNMMmmmmmddmmdmmdmMmoyMMmmmdmmyddydmmmNdmNMMhoydNNMMMMMNy'
echo '           -dMmdNMdy../+NMMNNdNNdNMMNMNNmNNmNNdNNdNNNh-:dMMNmNNdNmhdmhNmhmNmMMMMMMMMMMMMMM'
echo '          +NMmNMmo-:syso:-++oshddNMMsNMdNNdmNdmmmmmmNMhsdmMMMNdNmmNmmmNMNdNNhNMMMMMMMMMMMM'
echo '        `sMMMMMs-..--...`.-`.-..---:--+odNNmNMmNmmmmmmm-:-:sNMNdNmdmmdmNMMmmdmmdMMMMMMMMMM'
echo '       `yMMMMh-`-``-``-./o+o+-..`-``-``-`.:-/hyhmMNNmNM+-``-:mMmNNhNNdNNmMNdmmmNmMMNMMMMMM'
echo '      `yMMMN+..-...-+ydhhyooydy.-.`-.......-..-..+++sdd+.-..-:mMmdmmmmdmmMMNhNmhNNMMMMMMMM'
echo '      sMMMN/.``..:smds--`..``/yd:.`.``...`..``.`.-``....-:/+//odMMmmmmdNmMMMdNmdmNmMMNMMMM'
echo '     /MMMNs.`-`-hNyo.`-``-....:m/-``-``-``-``-`.+.-`.sshhyssosydNMNddMNNdMMMNmmNdmNNMMdNMM'
echo '    .mMMMs/`.-ymd/.-:::o/+y+:+-oy.`......`..`...m+.omNo:-...-..:-/ommdymNNMMNNNdmmdmMMNNMM'
echo '    sMMMm/hosmmyoshNNNNMMMMMNds+y``.`..`.``-``.`+ddMdo++++/:/.`.``-.+md:osNNMNNdNNdNMMMNmM'
echo '   -NMMM:./NMMNMMNNNNMNNmmNmmMNNy-`.-``-``-.`-.:hmMMMMMMMNNmmdhoo+...-hm:-:odmmmdmmdNNMNNN'
echo '   oMMMm.-yMMMMNmysNMy:......:hMo:.`.``-``.``../Nyo+:+:/ssyddmNNmhhs:-:mm/`.oMMmmNmmNmMNNm'
echo '  `dMMMo.dMNs/my-odms.`.``.``yNyhNdy+/....`-.`-:h-``.````.``--/mhmNNdh+:Nh...hMNNNdNmdMMMN'
echo '  .NMMm-sMMs`.:sss/-````````:Nh.-//sshs:``..`..--````.``.``.``+d::+sdMMhdN..-yMmMMMmNmNMMd'
echo '  /MMM+-mMN.````.``.``.``.`.dd-``-``-..-``.``.``.````.``.`````./yos+yNmMMN.`-sMmdNMMMNdMMd'
echo '  oMMd/-NMo`..-/+ossso-:``-:mo``-.`-.......-`.-``-``::/:-..`.``..:o+/:.hMN-..sMhmmdNMMNMMm'
echo '  sMN:..ym:`.:sy+/:/-...`..::..`..`..``.``..`...-..`.-/oysss:..```````/NNm..-yMmmmmmNmNNmd'
echo '  sMh...:-:``:--:---..-.`......`.-`..``-``..`-::.....-`.-.-++++``````-dMNs``-yMmdNmdNmdNmd'
echo ' `dm-`-:--..:-.-:-..-...`.-``.``..`......`...--``-.-...--......-``-``/o++.`..sMdmmdmmdmmmm'
echo ' oMh`-/.`.---..:..`..``.``-``.``..`..``..`..`..`.-.`.--..``.-...`.:.`..`..``.sMmmNmmNNmmmm'
echo '-NN/.-..`.:``-`.-``-.`..`......`.-`.-``-``..`...:..`-/.`-`.:.`-.-:....-`..``-yMmdmmdNNmmmd'
echo 'dMy-``.``..`..`...`..`..``.``.``..`..``.``..``.``.``.....-...`.-.`.``..`..`..yMmmNdmmNNmmM'
echo 'MM:-``-....`.........`..`.-``-`...`-.....`.-`.-``-``..``..`..`.-``-``..`..`..yMmmNdmNNNMMM'
echo 'Mm-.....``-``.``-``-``.``...`....-..-``-``-.`.``...``-``.``..`..``.....`.-``-yMNdmmdNNMMMM'
echo 'Md...`..`..`..``..`..-://+yoodsyhsyhoyy+o+::-..`..``..``..`..`..``.``..`..``.yMmmNmmNNMMMM'
echo 'Mh.-``-``-.`.....:+osdNNdsh+/+:-:--:-///osyydds/--`..........`.-``-``-.`-.`..yMmmmdmmNMMMM'
echo 'Mm..``..``.``.``-sdo::+++ohoydsyhyyyyyyyyyyhhmNmdyo.`-``-``.``.`.``.::-``.``-yMNdNmdNNMMMM'
echo 'MN-.....`.-`.-../mo/::/::///://::/::o/:o//+//+///+dd+-..-.`..`....``s-.`..`.:dMmmmmdNNmhmM'
echo 'NM/-``-``.``.`..:N+-/:-+--+--+--/--/-/::/:-+:-+--+-omy....`..``-``.`+-``-`...mMdmmdmmNd./d'
echo 'hMd-``..`..`..`./Ns+/:/::::::::::/-:/:-/::/:-/::::::sMs`-.`..`..--``-:-`..``:mMmdmmdNNN/--'
echo ':NMo......-`..``-/yhmhyhys//::/:-+--o/os/+s/+o/oooshNd/`-.`-.`../-`..o-`.-``+NMmdmmdNmm-..'
echo ' sMm:`-``.``.`..`.`./:/+///..+../`-dhsoo+shyhdydhso+/...`.``-``--/+///``-`..:NMdNNdNmmN.`-'
echo ' `hMN--.`..`....-.`..`.-..-.-+y- `.m/.`-...-`........-....`..`..`......`..``oMMmmmmmmmN:..'
echo '  `hMy.-``-``-``-``-``.`..`..`/h``:N/``-``-``.`..`.``-``-``-`.-`..`-.`-``-``sMMNdNNdNNM+.`'
echo '   `yMh-`..`.`....:--``-``-``-.d. :m-....``-``-``-`..`..`-``-``-``-``.``-``.sMNdNNdNmmM+`-'
echo '    yMMNo:..-.....::.``-`.-``--m. .N/.`..`.-`.-``-`......-`.-`.-``-.`...-...dMMdmmdmmmMy.o'
echo '   .NMMMMmh.`-``-`+:``:`..`.``+y ` hy``-``-``.`..`.``-``-``-``.`..`.``-``///NMMNdNNdNNMNyN'
echo '   oMMMMMMMNh/-.--y:..s-..-.`:d/ ` sd.`..`.-`.-.`-...-.`..`.-`.-..:-:/-`-..-mMNdmmmmmmMMMM'
echo '  `mMMMMMMMMMMdo-/:/s+/:``:``om.` `ds-``-``:``-``-`..`..`-``:.:shmNMMMmo:`./MMNdNNdNmmMMMM'
echo '  +MMMMMMMMMMMMMNhso--:-::-:-:do.`:m/``-``-..........:../.+ddNMMMMMMMMMMhs.oMNNNdNNdNNNMMM'
echo ' `dMMMMMMMMMMMMMMMMMNs/::::/::odmsd/+:-+::/::::::::--++yhMMMMMMMMMMMMMMMMMMMMmmmdmmdNmmMMM'
echo ' /MMMMMMMMMMMMMMMMMMMMMmo:o.-+.-+-//./:./-.+..+..+.ohNMMMMMMMMMMMMMMMMMMMMMMMMNdNNdNmmNMMM'
echo '`mMMMMMMMMMMMMMMMMMMMMMMMMhd/:/:-+::/:-+::::::-::oNMMMMMMMMMMMMMMMMMMMMMMMMMMmNmdNmmNNdMMM'

echo 'NNNNNNNNNNNNNNNd`   ``  ...-`  ``      .` `               ````..`            .sNNNNNNNNNNN'
echo 'NNNNNNNyhmNNNNy`   :.:    `/ ``       .` `.           `     ``  `.`       `` ``-yNNNNNNNNN'
echo 'NNNNNN:   `.:-`   --:`    ./.        ..   .           `      ``   `.`     `.`  ``/mNNNNNNN'
echo 'NNNNN:`...`              ../.       .-`   `           `       ``   `:`     `..` ``-hNNNNNN'
echo 'NNNN+ `...:  `.```       .-:.`     `--    `           ``       `    .:`     `--`  `-sNNNNN'
echo 'NNNh         `                ..` `--`    `           `` `           :-`   .-......--+hNNN'
echo 'NNNm:.``     ``       .::-.   `-``---     `     ``    .. `           .:-  -:`    -.   .NNN'
echo 'NNNdo/::/              `..`  ``:`---.     `     ``    .. ``          `::.`:.`    :-.   yNN'
echo 'Nms+/::/    `.`             ``-..-.-.     ``    `.    -.  -          --:::/-`    --.   /hN'
echo '+:----/    `-:.    `..```````--.:.`-.``         `.   `:.  -`       `-`                 .-+'
echo '----..+.`  `..    ``-:---..-:----``:.``         ..   `/-` -.       -``  ...`       ``     '
echo '..` ```::--..``  ``-:----:/:-..:```/``.`        ..`  .+-` .:     ``.``  --.-`        .  --'
echo '      `-/o/:::---.-:.-``.`..`.:.``-:.`.`        .-` `-/:` .:`    ` .``              ``   `'
echo '    `-::///--:::::-..` ..   `-:``-.--`..`       --` `:.+. ./`    ` -`...````       `      '
echo '  `---::o/..`...--.`` `..   `:-`--..:`.``   `   --` .:./. ./.   `` -//::::-.`     ``    :-'
echo '`-----/+-```..``--.`  `..`  ./..:..-+`..``  `  `--.`.:../`.:.   ````:-----/``    ---    +:'
echo '-----/-`  `..` `:-` ``-::-..-+-:-```:.`.``` `` `-:.`--../`.:.` ````.:---.-/``    --.    /.'
echo '----.`  ``..`  .::`   .--`` ./.`    .:`..````` `.:-.:.-.::.-.` ````---:..-/`.``````````--.'
echo '--.`   `...`   .::`  `.:..` ./.     `:.``.```.` ./..:.`  :::/-`````:..:.--/::::::--:::/:..'
echo '-`   `.---`    .::.  `-:+s.``++:` `. `:``..``.``./.-:`   `:.:``--.:-..:.-.-----::::++.....'
echo '..--:---.:`    .:::  `ydo:/``+o+oy:`` `:``.-`````/---     `::`````/-.`:-.`----.-----+-..``'
echo '..`----/+:     `-/:. ./..hNs`sNNd:+/ ``.-``.-````-/:.``````./-```-+.``:-``.-.-``-.`.::::..'
echo ' `---/+++/ -`  `-:/+`:` smNNs/NNNm :````.-``.:````/:`/hdhyyyy/```/-- `:-` `.`-``.-``.+----'
echo '.-:+o+:/+/`+/   .-/hs-  hhddMdNmmm    ````-``--.``:+o/.+hmNNmy``-/.:``:.   .`-` `-. `./---'
echo '/oo+/:/+++-//-  `-/yh`  /s++yhsoso     `` `.`.`--`.+`.hNNNNNNm.`/No.-`/`   ``.  `:-`  .:::'
echo 's+/:::+++s/::/. `--+/`   :+o++oo/          ```-``-`: /mNNMMNNN::`+N/+./`    `.  `::-`  .::'
echo '+/:::/oy+o/----` --/       `..`              `.` `...+sshNNddms-`:my///    `..  `/--:`  .-'
echo ':::::omdo+..----`.-/`     `-:-`                  ` `..s////+oy: `sh+-+/    `.:` `/--.--` -'
echo '::::smNms/``.----`//``                                `:/++/:`  +y-+-::   `.oo- `/--...--`'
echo ':::ymNNNh-` .-----:o                                  .:-      .-`+:-:.  `./y+/`.---.-...-'
echo '::hNNNNNh.  `------y`                   `               `       `:+--/` `.:-s//:-``----...'
echo ':ymmmmmNy.  `.--..-so`                  `                    ```:.+.-/ `.:--s::+o. `.---.`'
echo 'ymmmmmmms.   `.--`.soo`                                     ```s/+:.--`.:---s:::+s.  `.:/-'
echo 'mmmmmmmm/.    `-:.`osdy:                                     .oo+s-.:`--..-.s::::+y:   `dy'
echo 'mmmmmmmd:.     .:-`/mmdoo:`         `---..`                 :o+++s.-:...`.-`y/::::hmo`  om'
echo 'mmmmmmmy-.`    `-:-.mmmd/+s+`          ````              `:so+++os-:- ```--`do::::hmmd- `d'
echo 'mmmmmmmo--`     `/-.hmmmh+ymmo:`                      .:sdmdo+++o+.:`   .-``dm+:::dmmmmo`+'
echo 'mmmmmmm+.-`      `/-ommmmydmmmms-.`             `.:oo+smmmmmo+++y:-:   `.. .mmm+:/mmNNNNd:'
echo 'mmmmdhy:.-.``     .//mmmmmmdhys+``---.```...--:oydmmsymmmmmmyooyd:/.   `.` -mNNm//NNNNNNNN'
echo 'ho++ssy:`--` `     -:ymmm+-`-:-:..```.---....--/:-./hmmmmmmds++sy::   ``` `/mNNNdoNNNNNNNN'
echo '`-:o+/+:`.-:````    :+shy  ````````````````````-.-.``mmmhs+/////s/.   ``  `+sydNNmNNNNNNNN'

echo '                                 `-:/:::--``   `.---...`  .--`                            '
echo '                            .....`                     .---` -/.                          '
echo '                        ....````          `````````        .--`:+                         '
echo '                     ...    ```     ````````````````````.`    .-:y.`                      '
echo '                  .-.      `.``    ..````````````````````::``   `:.-..`                   '
echo '               `--`     `..`   `...``--```o`````````..````./-```  .:-://:--...`           '
echo '             `--` `.` `..````.--```-:.```.+``:```````-.`````-:````  /.        `.....`     '
echo '           `--`.:+- .-.````--```.--````.:+-``:```.````:````.`.:````  :-```         `.---  '
echo '          -------`.-`````::.``.:-```.:o/.:-``/```-`````:````..`:````` /.`````         `./:'
echo '        ./-.`.-.::.````-+:..:o+.`--:::.``-/``+`..`-````-.````-..:``````+```````          :'
echo '       .-`  -::o:`-.``/s.-:///:/+---``````o``s````:`````:``...:`-:````..:-```````        /'
echo '          .:-./. :.`:oo/:--/:...-.````````+``+/```.-````:.``.`--`/.`````+.:.``````      `:'
echo '          .``:` :..sddhhys+-....``````````-:`//.```/`````:`````-.`/`````/.`:.``````    .- '
echo '            :` :..yh./..y/+yy+.````````````+-+:+-.`/.````:``.```:`/.````:-``:``````   ..  '
echo '           :` .--hyy  `./``s.+o.```````````-::`.+--:s````:``-```:``/````::`.-````  `.-`   '
echo '          -` `:-yoo/` `````...o.````````````/+---/``d-```-.`:````:`+``..::`````  `.-`     '
echo '         `. `:-o+:s........`````````````-/+ooo/-.-/.o+```.-`:````:`/-..`s````   ``/`      '
echo '         - ./+::`-: `....`...``. ```````.-::oy+syyss/+```-:`/````/`.+.`:o````    -.       '
echo '        ``.:-::``+  ``````````..```````````.:.`.o:sddo-``:-`/````/.`+``y.````  `-.        '
echo '        .-. :-:``/  ```````````````````````````.:.`oomd/`o.`:```./+`/`/o````.-/-`         '
echo '       .-   -:```:  `````````````````````........`.--oy/:h``:```:+/.:./+/.-/:-/           '
echo '       `     /``:/  ````-.````````````````.........`.o:`:o.`:```:+`/::`//-`-`.-           '
echo '            `:.:`:` ``````..``````````````````.``...+-:.+`:.-```:/`+/`-.+``- :            '
echo '            .-:   :` ```````````....````..````````.-/`-/.///```:.///o`-./``- -            '
echo '            -:     :` `````````````````..``````````/``-.:-/s```/://`--`-``-``.            '
echo '            .       -. ```````````````````````````:```.:.`o.:``+/:``..````. -             '
echo '                     -. `````````````````````````:.`.:/..---+`.o/```..```.``-             '
echo '                      `-```````````````````````-/.`::..//--//`/s````-`````.:              '
echo '                        .-`````````````.``.````:--+/+:-`   :`//:``.-`````.--              '
echo '                          ....../yyyyy+:..```./-/ `:-.    -.`+.``.-`````./:               '
echo '                                .++:-````````-.`:` -.    .-``..`--`````:`+-               '
echo '                                -``````````````-hyso:   `:.``-`:.```` +/-s                '
echo '                                : ```.-/+oosssyyyhyy-   ::``:`:.`-`` --+-o                '
echo '                               ::-/+syyyyyyyyyyyyyhy`   s``s.:.`-`` .: :-+                '
echo '                           `-/shysoooosyyyyyyyyyyyyys   y ://.`:`` .-   -+`               '
echo '                         /yyyyo+/::/syo//osyyyyyyyyyys/ +..:+``:` .-     `/`              '


echo '    .so//-..+`.-/` `        `       `+++so++++++++++++ .sys/.-/.``.   `/-..`:s+`       -.-'
echo ' `-:/+y++`  ..``                    .+++++++oossssssoso+oy+ `   `` ``.` `-`.so`   `   `./:'
echo '/+::--.:o///+:-...-.`              .sso+++//:--::::/+++oooo--. .::///-  `.`:+    `   ` -:`'
echo '+::/:-.`/--.--````:`:         `-:/+/:-----------:::-----:///:::/+-` `/---:`/   `.  `..--. '
echo '-----.-/`..-.``-:/+:+-    `-:::--------------------///:---:++++/::/:.-:--:-    os+/-.--. `'
echo '.:...--/.```-//:/+://::`-::----::--------------------:/+/:-+++++++//:::-::    /ydhso/--.``'
echo '......-:/:-::s/-` `.:o/:-----::-----------------::------+o+++++++++++/:::    .shdddhso+--.'
echo '..--:y+/++///....-:o+:------::-----------------:::/--.`--:o++++++oo++++/::.`.+yddddddhso::'
echo '/-:::-.`.``````..-:--------::----------::-------/::+------/so++++++oo++++/:/+sdddddddddyo+'
echo '````````..--:::/:.--------:/------------o/------:+::+---:+++ss++++++oso++++sshddddddddddhs'
echo '```.-::/::::::+..----:----:.----------:--y/------o+:/o/++++++ys+++++++ssossshddddddddddddh'
echo '--:::::::::://`.-----:----:.-----------/-/+:-----++o+oyo+++++oyo+++++++ssyhddddddddddddddd'
echo '/::::::::::::`.-----:------------------s/-+::--:/+++o+ss++++++oysooosyyhhdddddddddddhssydd'
echo '+////oss+//:.`------/------..-/:-----.-os:/:://+o+++ooo/o++++++shhhhhdddddddddddddho/-.:+y'
echo ':::/+++:::::`------:o-----:```/:-------oo/:o.++++++++o+/-o++++++hddddddddddddddddhs.-.-:.-'
echo '/+/://+:://.---.---/s-----+`.-:+-------oo/+s`.o++++++++:`/++++++sddddddddddhyoo+yyo.-  ``:'
echo ':-...`://./`---.---+y/----o----o------:o+//o.`///////:+.``o+++++ohysyhddddho+++/:s+:.  `++'
echo '``````.+:/.`--.`--:+so/---+:.--o/-----/+++.s.`-/shddhhho:`-o++++osso+osdhyoo++++:o+/--.:++'
echo '```..`-s`+.-------++++o/-:/-:--:s-----/++o`o`:hhsssso/-/s+`+++++ooso+++oyo+o++++//+o:/::::'
echo '```oo:+::+---::---+++-ss/::/.---++---:++++`.-d+-dNMNNms` ...o+++o+s:-:+++++++++++:oo....``'
echo '``:dhys/s+-:-/:+:-++s`-o+/-/..--:/+//+++++ `oo`/MMNmdhhs    ++++o+o-.../++++o++++/oo.````.'
echo '-/hdddd/d+-////+/-++o. ./:::/..:++:o+++++:` -` .Nhsso++o:   -o++oos+:.- o++++++++/+o:````-'
echo '/ydddddodo-/o+++o-/++:`:shysss+-:++.+o++/.      /s+//::+/`  `s+++os/-.. +++++o++++/s+````-'
echo 'yddddddydh-:os:oo/:+++:ms-:hmmh+``:: .:.`        :o+/+oo:``  s+++oo:-.``o+++++++++/oo````:'
echo 'dhyhdddddd/-+o+++s//+o+m.`oMMNNm+  ``            `-//:-.``   +++os+/.`-.o+++++/+++++y````-'
echo '/-.-oddddds::+o/+os//+ss. -Nmhsss-                ````      `:o+oo+/`-`+++++++/:+++/y+```.'
echo '-:::-ods++o+:/+o+oos+/o/`  /s++//o                          .`s+oo++..:o++o++++-/++++s+-::'
echo '/:::::/::::+++/++ooossos-   :o/://`  `                      . o+s++/`-s++++++++/-/++/o++::'
echo '::::::::::::/++o++ososyyy-  `-+:.`   ``            ``      `` ++s+++/+o+++/+++++--/++/o++:'
echo '....--:::::::/+oosoooossyy-`.```              ``.--::-    `.  /os++so+o+++/:++++:--++/o+++'
echo '...``````...--:++oso++++osy.`            ``...-------:-   `   :so++so+s++++::++++--:++++-:'
echo '`````````````.:-`.-//::s++oo           .-----...``````-       -so++ss+oo+++/-:+++:--:+++--'
echo '````````````..```````.os/::o`          ::-..`````````        .+yo++ss+os+/++:-:+++---:++/-'
echo '::-`````````````````.oo//--:+`         `-.```````         `.-..y+++ss++/-..:/--:/+:---:++/'
echo '::/+:.``````````````+o:/:--:+o:.         ```            `...```s+++o+--..`  -::::/+:---:++'
echo ':::+os+:`````````.-++.`/--::/so++/.``                 `-:.````.s+:/-`  .+/`  .so:/--/:--/+'
echo '::::oooo:````-+o..-/.``+--/-/yo+++oo+/:-.`         `-//-.```.-:o-` `--`  ...   .:`  `:/--/'
echo '::::+oooo.````ys`./:``::--/-/ys++++o+++oo+///:-..:o+/:-``..:-:----`   `         -`    ./:-'
echo '/:::+oooo-``  .o`:/.``+---+-/yso+++oo++oo+++sssssy+:-.`.-:-.-..` `..`        ```-`      ::'
echo 's++oooooo.``..`/`::-`::--:+-+sss+++oo++so++oysoo/-o:--::-...-.:/`          `````-        :'
echo 'osossss+` `...--:/-:./---++-osss+++:o+os+++sss:..-+-.````..----:+     `````````-   `.    `'
echo 'os+ooo/  `-:`  `.+-//---:++-ysss+++-ooss++oso/.o:-.       `:..-/.    ``````````- `..      '
echo 'os++o:  `.`  `.--` `+:-:+++:hsss+o-:osss+sdh-/os+oy+      .-..-:    ``````````-`...       '
echo 'os+o. `.`  `...   `.--:+++/+ysss+/`+syhdmNy-o++++syy:     -.:sh`   ```````````:....`      '
echo 'osss.     ```   ...   :+++:yssss+-:ymNNNd/.:o++osys::.   `/ohd+    ``````````:.....       '
echo '+-+//          ``  `--.o+o:hssss:-smNNmo-::+ssyys/.../ `/shhhd/   ``````````.:.-...       '
echo '//+/:/`           `-/-/+++sssso::hddmd+--:+oooyy   ``:oyhhhhhhy`  ``````````:::...-       '
echo 'ooo+-//`           `./o+++hss/.+dhhhhd::/+sy+oyo   ./yhhhhhhhhdy- `````````--o//-.-`     `'

echo '   `.``    .-/oshdNMMMMMMMMMMMdo-`        `   `s`+o-   -y+  ``.-://+oooooys               '
echo '+oo+oshdmNMMMMMMMMMMMMMMMMMd+.          ``    /.   :+/.  :o`        `     -o              '
echo 'MMMMMMMMMMMMMMMMMMMMMMMMNs.             `    `o      `//:` ..        .`    /:             '
echo 'MMMMMMMMMMMMMMMMMMMMMMNo`              `     +`         `:/-`-        -`    s             '
echo 'MMMMMMMMMMMMMMMMMMMMNo`               .     .+              .-+.       :    s`            '
echo 'MMMMMMMMMMMMMMMMMMMy`                ``     s                  -/      `:   :/            '
echo 'MMMMMMMMMMMMMMMMNh:                 ` ./o+ +:               `   `/.     -.   o-           '
echo 'MMMMMMNNMMMMMdo:`                        `.o++////::-..`    + `   /+     +   `y           '
echo 'mmmNmmmmmmyh-  .                  -      `:                 :-`    +y    +h.  //          '
echo '  `:     -o`                    ::.     `/                          +:   /MN/  s          '
echo '  /     :: ..`                /so`     -+         ``                 /   .MMMh.::         '
echo ' /.    /:`:`               `//:s.     :+..so:-``````       `.      :/-:.  sNMMNsy         '
echo '`s/   :/:-               ./:``s.     /-. ::            ..-smd/+ohdNy-`/-.:hsMMMMN`        '
echo ':s.  -y/`             `:+-  `y.    ./`  .         `...-+yNMMMMMMMMMMMMM+No.hhMMMM.        '
echo 'o.   h:             .//`   `o`    /:           `/-`-odMMNhs+///+osyymMMy:  -dhMMM.       .'
echo 'y   +.           `/hmo+/:.`o`   -/`             `/yMNdyo/:::/-      hNy/`  ..mddM.   `//+o'
echo 'o  /`          :/:.:     -s   :/` `           `-omh/:y/-----.:s+   oNy`:- `` -MsM..odN` `/'
echo '+ /`        `os`        .+  .:`   --`        .+ho`  h.-.:o/-+:.h++dNh+`/` -   yyNmMMMd  -:'
echo 'y/`       -/+d`  .-+/-.// --` ..            -s/    `y/+++y+-/.:+yss/:.`+ -    +msMMMMy  s`'
echo '/.     `.:. :+  ``    :-::     `-           :`   `-/sdsyhNmmd++y+//+/-:o:     /MyMMMMs /- '
echo '/     .`.`  y``  `/`.+/:`        .              .:..-.`.-./MMMMMMMMMMNm/      +MyMMMMo/o  '
echo '     -..   `yyyyhdNMMMMNmNmds+/:` .   ``.`````.-..-/--:-:--yNNMMMMMMMMMh.     ddNMMMMoM/  '
echo '   `/-...:/oMMMMNNhyyoos+y/mo+::::`-`.-:-..-:-:---::::::://+/shmNNmdMMMMMo   -MyMMMMmhM+  '
echo '   +:-/shdsMMMN/`d-`:hosos/s/:/---::-:/--..-::---....--:--..-:-.-:dysMMMMMs` hmmMMMMsMM/  '
echo '  +.    .yMMNhdmyhyys/dy/-..-----:::::--.--.`..```     ./:.--/+++/..+omMMMMd/MhMMMMmhMd   '
echo ' /`   .sMMMddy-/odo/-:-:::::..-/-::-..: `.`              :///:.``    :sdMMMMNhyMMMMsMh`   '
echo '--  -:.sMMMyMN/--:----::::--:-.:/.`  `/                       `.-:sd+//yhMMMMNhdMMhhh``-:+'
echo '/-::`  hMMMmMMh-.:+oo+ooooymNNMMNd  ````                            .--yhsMMMMMmymdy ..  :'
echo '+.     yMMMsdMM:oMMMMMMMMMMNNhhmy`   ``/                       :``    /ddMMMMMMMMdMs    . '
echo '       `NMMMhMMhMMMMyhmNNNNMMdo.                              `-.   .hdsMMMMMMMMMmm.   -  '
echo '       .sMMMNdMmMMMMmMmdyo/-`                           -+`        :NMyMMMMMMMMMMM.  .-   '
echo '      :- dMMMdhNMMMdMo                        `.-::/.mmMMm`       sMMmdMMMMMMMMMds  :.    '
echo '    .-`  yMMMmhMMMdmd             ``  .::..``   ./hN/y+sMo      .+NMMhMMMMMMMMMh:--:     `'
echo '  `...-.`sMMNdMMMNhMN/            .sNMMMmhsooshNMMMN+`.-h`     .yNMMNdMMMMMMMMh/-+-   `..`'
echo ':oo+:::/sNMsMMMMMyNMMmy` ..`        -dMNo:...--:+os--.-//     -NMMMMdNMMMMMMMm/./`  --.   '
echo '.        oMhMMMMMNymMy:yo-:.          +d:.``...`//.---:y`   -yMMMMMmhMMMMMNh+`.` `:-`     '
echo '   `     `mmMMMMMMNyMMh`.sy:`           :////--..`.-:+o`  -hMMMMMmhNMMNy/.   - ./-        '
echo '   :-     .mMMMMMMMNmMMN: .ymy/-`          `.:+++o++/`  .hMMMMMMMhMmo-     `--y/          '
echo '           :MMMMMMMMMsMMMh.-+hMNmyo+`      - .`        /NMMMMMMMmo-       `ohy.       `   '
echo '            +MMMMMMMMmoNMMNy  :d:  `:yo:`  . /        :MMMMMMMd:         `s/d         `   '
echo '             dMMMMMMMMNyNMMMy:y/o+`  `- -o+.--       :NMMMMMh:           + :o        +.-  '
echo '             :MMMMMMMMMMyNMMM:NMMMNs`.` :/MMdy+-.`-/oyMMMMm-.           /  .`        /-   '
echo ' `...-+o//o`  dMMMMMMMMMNdMMMdoMMho/+y/`/hMMMMMMMMN+`dMMMh`-           +` ..              '
echo '`-    -   --  /MMMMMMMMMMdMMMM+MMd` :---..-+-yMNy+`.hMMMm`-`          -d  /`              '
echo '-        .:    dMMMMMMMMMNdMMM/MMMmNs   o/-/  -+` -/-hMMy -          `mm  s`              '

echo '      -o   `//          `-+yhs:.   -mN.    +``:+/`:.-.     .:--..`     +y-:++/.   .+y:    '
echo 'yyyssds     `.//`            .://:` .mo    `s`   :.`  `::::.        .-.+-    `/++/:ss:    '
echo '  `-os    .-.  `/+:`             `://+y.    /o- -` .:/:`         .-:::::os.     `:o+- .+s+'
echo '-/-`s` .--`      oMNs:-.             `:s/.   :`  ./:`        `-oo-       `..       `/+.   '
echo '`  +::-`       -yy/.` `-://+:..`        `:o/`..`:`        .-:++:         /+`-.       `/o. '
echo ' /s/`        .:y.   `..:/::.``-:oo:-..-+o/:.`-y:/y:-:-://:.:++`       `+y-    --`      .s:'
echo '+.          :.`-  `::--`    .-++`    :-       ` `-``` .++yo` `:-`   .:+y.`     `+o::-`   +'
echo '          .:`   .--.`.---://.--   `//`                   `:+`   `-. ``ods-       ./.`-:-  '
echo '---.....-/o::-:+/////-.``  `-` `:/:`                   `:  `-/:`  `:- `/`.         ::  `:.'
echo '.----......`````          .--:/:.` -. .--`              .     `:/:` `--  `-`        -:`  :'
echo '                       `-/o:.`      .  `:s+++/:--.`             `:y/-`.:.  ..        ./`  '
echo '                     -/+.         -`       ```````               :s`.y/-::  .:        `/  '
echo '`                `:+h+`    .:     --`      `....` ``              ./ `s:.-:-.`-`       `/-'
echo '/+/+:-....`.-::+h/../      s-     ..   .-`.:y+-`` `     `:/--:s:.`.s//o/:  -:/-+.       /y'
echo '`:o:..-://+-...:: `-      -+               .`      -:/sdmNmdmNNmmmNhs+` y+  `---+:.     `:'
echo '/.      `/`   ..  s`     .:                     .-:+hdhs+:-...-yMNo`o+ -:-+   `-.`.::.    '
echo '     `.:d:  .-`  /h    `.. `oo:. `            .-./syo/-//-+y-+dNd/  :+ :s+so    --  `-/:. '
echo '  `--.`-h `--`.--ss   .-` -:.``` .-`          `.++..s+ohhydNNNhy:---./ +/.-y/    .:    .:/'
echo '.--`   /+++::-.``mh   ` `osssoo:` `--         `:..-+hdhdmdhys+//+//.`. dm.:.d`    .:     `'
echo '-` .//+y/-.`    /:s. .+sdNdhyyyyso/..:     ``.--://++osooo+o+o+//+:--..+/ :.N:     +`     '
echo '    ``-/       `+ .s:+mMd/.  `--:-/oo-``./o+/+//:/+o+++/o+/+:--.:. ``  // `+oo `..-s`     '
echo '      +.       +`  sNMMo`   ---::/+ .:/+yhy+/:--::--.....``    ..`    -+-/shss//+++/:--.``'
echo '      o       -/.-/hMMy    `o.sh/`o``+yso+-.````              `+-  `./sss+//////////++++os'
echo '     `o       s`.-/hNMh`   :s+::-/s/os/.-`                     .`-+o+/:-.`.--:.-...```.--:'
echo '     .+      -o     :NMh-````/ydhyyo:.``/.                    `://::::::--:::::::::--..`..'
echo '     .+     -./      /mmmhssyddy++:.``  `-              ``    o+:-:::///:::::::::-::-:-:--'
echo '  .:/-o    :../       +++dyho++::.`          ``.-::/+hhhdm/  .d//+osyyyshyss+//:::-:::----'
echo '/o/. `s   /. `o       .s+:/++/..`           ....-:oyhMMMMMN- `+o+-` `.d/...-+hs+ss/-------'
echo '/`   `y  -:   s      `--h/:/-.`          -+..:ohNMMMMNNNmmNs         :y `++` .:///os+-----'
echo '-`    o` o    s`     :  :s```           .dNNNMMMMMMMMh+-.:/y        `h-  `+/:.     `so+:..'
echo ':/:.` -:.+    :/    -.   //`            `:yMMMNmmdddh::`.::s       `o/-    :--:.    `//os:'
echo '  ./+/:y:+     s`   /    :-o-`             +Nm/.-:::o::--://      `o-   ``.`/- -/`      -s'
echo '     `-o+s     -o   /   ./:`:yo:://///:.`   -s/..::-+::-:+o      -+--       `/+.`/`       '
echo '--.`    +:o-`   :+` :-`````.sd+.`     `:+/.   s/-.:::::.os`     -d` .:        `:++-       '
echo '  .---` `/`:++/-.:y:`.---:sd:            `+:  `s/::::-:.s`    `-y+   `:          -:`   ``.'
echo '      .---`   `-:/://::-.+h`               -:   :++/::--o:  `::`h/+.  `:           .-os+/:'
echo '-        `:+`           .h.                 .y+:.``..-:/// .o.  d/`o/  --        `:`-`-+/`'
echo ':o`         -:`         s:       /+o+/-`     ss-+ddy+-` `.//   .y:`/ms  +      `:/so /  `o'
echo ' `o-          +s-`     -d `-.`  `dmMNNNm+    -m: `h:.-//+/`    o:-d+``  /    `/:` .m.:.  `'
echo '   o/          s+/+++++hdomMMNmddMMMMMMNNdyo-`s-.:Mo          -y`.sy/``:o::/y/`    s+`/  -'
echo '    /o          s-    :dMMMMMMdmMMMMMNNNNNNMMms/.+++/::-` `/-:s:`.-MMNo.  :/`      -d`/ `h'
echo 's+so+y+         `y`  hMMMMmNmhMMMMMMMMMMMmMMMMNNmdy:::``y s-    oMMMMMo -o-        `m/+ `s'

echo '        `y/    .o/`             `-+ymNho:-`   `/mMh      -o `:+so- +- :.        .--:---`       /m+:+ss/.      `/yy.     '
echo '++oossyyh:       -o/`                `:+++:`    -NN-      +-      :-`-     `-///:`          `-/d.    `.+ss/``/yNs:-     '
echo '+///:-/d/      `-- -o+.                  `-+oo/. -No      .d:    :-    `:++/.             :oo-`-o.       `:sy+.-s-     .'
echo '   .:/m+     .--`    .+s+.                   `-+oooh-      /o+` -`  ./++-`             -:/.`.-:/+ho`        `:ss:  :+dy+'
echo '`/+-`/o   .-:-         +MNdo-.`                  `-+ho-     /`.   -++.             `:so-`        `..`          .+s:  `  '
echo '/.  .o`.::-`         `sNds/:-:++//-.`               `./oo.  .- `- .`           `-/+oh/            -/.-.          `/o-   '
echo '   -y+/-`          `+ds-`     `.--:syo/::/:::-....` .///+s/``+. -:`        .-:/:-/o/`           .oo.  .--          `os. '
echo ' :ss:`           `::s:     ...-:/:-.` ```.:o+-..`` /o+/--.``-os/:h+/://:/oo/-`./oo-           -sd:      .:-`         :y:'
echo 'o/.             -/``/    .---:-``     `./s:`     `/-         `` `-: ``` `oyoys:` `-/-`     `-+oh-         .ss/::.     .y'
echo '`             `:-      -/:-.`   `.-/+//:+.     `//.                      ```:oo:    `...  `:--ms+o-        `:/..-//-`  `'
echo '             ./`    .-::--://+///:-.` -:`    -++-                             `+:.     .:-`  `ym+`           ./-  `-/:` '
echo '::-----..---/s/:::/+s+++/:--.``     `-.  `-+o:.                           -:`   .:+:.    ./-` -- ..            /+`   ./.'
echo ':::::::--------..```               `-`.-/+/-`  :`  ..`                    ..      `-/+:.   .:.`   --`           -/.   `+'
echo '                                 ./s++/:.      `:. .:+ss/:--..`                      `:ys:.  ./-   `:`           `+-   `'
echo '                              `:+/-.`        `        .:::+++++///:`                   -h//+:``-:`   --           `+.   '
echo '                           `-/o/`            -```                                      /y. .ys/--/-   -:`          `+.  '
echo '                        `-+hy-       /       -`-`                  ``                   .+. `++---/:.` `:`          `+..'
echo 'o/-.``             `.:++++/y`       -h       -::`    .``-:oyso/:.``.`        .    `-`    .s`.oho. `.://-.:.          -yh'
echo '`-:shso+/:////::++o++dy` `-`        s/              `-`   //.          ``.-:smoosydmo+::+sNs:s `s-  `-:::/y-          s/'
echo '`:o+. ``.--::s:.``  ./  `+`        :o                     `        `.:++omMMNNmmNNNNNMMMMmsso` `hy/   `--.-++-`       .-'
echo 's:`         ::     .:   +/        -+                             `://+ydmds+:-``...-oNMMd. yy  -+`o:    `:- `.:/:`      '
echo '         `:ys    `-.   .m-       --  ./:.`                    `-:-./dmy+/:/://+-  .sNMNs`  oo  +o:`d:     ./`   -/+:`   '
echo '      `::-oN.   -:`  `.ym`     .:`  .sy+/:``-`               `/.`/hh/.+-./yo-/sNsyNNMh/.  `-y  :+y+sm-     `/-    `:oo- '
echo '   `:/-`  ss  ./- `-/-.hh    `-.  `/:`      `::                -so. `oyssshhhmNMMMmss:.:::--o `o+` -sh`      /-      ./o'
echo ' .::.     s-:++:///.  -Nm`   -   .s+ooo+/-`   ./.             -+`  `:smmmmNNmdmdh+::/++//.  .`.NMs /-so       +.        '
echo '+:`  ``.-+dyy+:.`     yom/   ``./mNdmdmmmmy+-`  :/            ``-/+ssy++oosss+//:+s+/////-:-.:`my. +`om`      `o        '
echo '    .+oo/h-          -o :y  `smMMMNy+/::-:/oymy/`./     `.`.://:+::-+/oos+/+++hyo++/::+/--.. : :/` -.dM-       s`       '
echo '        `h           o. `y+/odNMm/`    `.::- `:sd/````:oys+/++//::+so//++/oy+:::-.--.`:        o+`  s.y/  ..-:oh`       '
echo '        :+          /+   -mNMMMs`    `/+:::+o+- `-::/shhho+o/:--/+/-::-.-...```      -`.      o: `-yh+d+::+o+/-.``      '
echo '        o.         `s`   .mMMMo      /. :oo:.+s  `+yhysy+:.``.-````                 +--      .dydddyysoo++o+++ossyysyoss'
echo '        s`         o:.+ohNMMMN`     `y//yhd- -/`.ohy+:/.```                        `+/`  `-+yyo/:-....-:-::------:::::/+'
echo '       `y`        -h  ``./dMMMo     :sy+..`-oh+oss+-...`                              ./oho+:-:-```.--::..-..```  ``-:::'
echo '       .y        `s/      `+MMMy. `.` `-yhmmhyhs/-.``-o`                            .++::::--:-:---::::::::-::::-..` ``.'
echo '       .o       `.+:        oMMMh+:..-+dNmhooo/-```   :/                           +y:::-::-:::::::::::::::-::-:-::----.'
echo '      `-s      `/`/.         shhmNNNNNmyys++/..`       `             ````..-:`    /h::-::::/++o+/::-:--::::::-::-::-:--:'
echo '   ./o:-y     `+` +-         `y:-shsy++++::-.`               `.-://++/hNNNNNMd.   sd/:+yyyydhhysddhhhso++/:::---:-:---:-'
echo '-+s+-` .h    `+.  +:          :y+//+/++/-..``              .:-.```-+ssdMMMMMMMd`  .syy+-.````+N:.``../dho+/sy:----------'
echo 'h+.    `h`   o-   :+         -.sd/:+++:-.              `:  ` `-+ymNMMMNNMMMMMMM:             ho `+:`  `+syyyhyh+-----:--'
echo '`       h-  -+    .s        `: `sy:--.```              sh/++ymNMMMMMMMMmmdssosNo            :d`  .sy:.   `````:sh+:----.'
echo '/`      +/  y`     h`       :`  `h+  `                +NMMMMMMMMMMMMMMms/- `:-ss           .m+    `+/:/.        /h++/-..'
echo ':o+-`   .s -s      ++      -:    `y:                  ./hMMMMMMNNNmNNNo::. .::+y          `so/-     ::`:/-       :oooo+.'
echo '  .+s+-` y`/o      `h`     +`     +/o`                  `oNMNho//////h/::-`::-++         `s/    `..``:/ `:+.       `./yy'
echo '    `-:+omy:s       +s    `/     ::.+++.`                 /mm:` .:::.y::::-:::s`        .s+       ``.-//` `+-          +'
echo '        `-y/h.      `s:   ./    `+/:``/dho/++++++++/:.     .os:..:-:-+/::-:/os-        /s.--          `+s/.`/-          '
echo ':-.`      .s-y:`     `s:   +-     ` `:hms:.`     ``.:oo:`    /y:-.:::/:::-.sy:        +d.  -:           `:oo-o          '
echo ' .-::-.    :/.+o+:.`  `++. `-:::::+sdd+.              `/s:    +s:--::::::.-y:       `-m+    .+`            -oy`         '
echo '     .-:-.` :.  -/+ooo+ohho:......-hy.                  `+/    +s/:::::--..y`     `/:+N/.    .:              .:```..-:+o'
echo '         .-:.-`     `..-..-::::---dy`                     /:    ./oo//:::--oo    -+- :h.s/`   ./               .-+hy+:-.'
echo '.           .:o/`                oy`                       -s+-.`  `.--::++os  `o+`  /m-`oy.   /-            `. :``/o+. '
echo 'o+`            -/-`             -d`         ``````          yd+oyys+:.`      `/o.    yh/  +m+   o          ./sm- /`  -oo'
echo ' /s.             :+:`           h/         `hmmmmdhs/`      :N/ `/dMdhs+:--:oo:     .d-`-shyy`  o`       .+/. hs ./    /'
echo '  `y+`             +do-`       :N` `:-.``` `hmmMNNNNNd:     `dd:  .d/  `-/++:       oo..ms`     +`   ``.++`   /N- o`   `'
echo '   `ss`             oy/oos+++osmN-smMMMNmdyhNMMMMMMNNNNhss:` s:/. hMo              .d.: sh/.   -s://+sho`     `ds :-   .'
echo '     /y`            `y/  ``..`.hMMMMMMMMNdNMMMMMMNNNNNNNNNNmo/y`--ymmo:.`       ```y+ - .NMMdyo+:`  //.        +m``/  `d'
echo ':::-  /h`            `h:    `omMMMMMMMMMddMMMMMMMMMMMMMMMMMMMm/s-/+` .--///-  so::/+:./+/mMMMs    :s-          -N/`o  +s'
echo 'o/+syyoyy             `h`  `dMMMMMMdNMyyMMMMMMMMMMMMMMNmMMMMMMMMMmMh+///` :y`:h`     -NMMMMMMN: .y/             dd.o  +o'


echo ':--..```.....://osy/````` `.`          ``````   ````` .``-`.----../yMMNNmdhysoo//:--`     ```````.     `sy.y..---+MMMs s'
echo ':://+oyyhddmNNMMMMMMNho:.```./:`   .```         ``` `````` `` `--::-..````````````  .`     ````.``-     :od:``.-.-NMMd`s'
echo 'MMMMMMMMMMMMMMMMMMMMMNyo-``.-:+ss---...`````    ``   ``` `...-.                 ``` `.`     -````` ``    ys ``  `.dMMN.s'
echo 'MMMMMMMMMMMMMMMMMMMMMNNNNmds+:--` ````             ```.--.`                          `.`     -``  ` `.   ..  `  .`yMMM:s'
echo 'MMMMMMMMMMMMMMMNmdhyysoo+:-`:-`...` ````....`.....``                            `    ``-`    `.````.  ``  -``` ``.+MMMos'
echo 'MNmdhyys+/+/-..````````     .                              ``                         ``.`    -``  .-      -````..-MMMhs'
echo '```   o  `-``````                                                  ..`````````        `.`:`    :``  .-`     -`    `NMMmy'
echo '     :+ `-`````                       ``.                       `..``              `.:/+``:    ..``  --.     :`    hMMMh'
echo '    `+-`:``                                                   `.`       .--::://:///:/+`  `-    .  `  --..`   --   oMMMN'
echo '    /.`-.`                                                  ````   `..:/++//+/-..--:::+/- `::  `      `/ .:-.. `-.`:MMMM'
echo '    /  -     ``        ````                                 ``    `--///++/:.``  `-:/:.-:+-`+.   .``   .. :```.....-MMMM'
echo '   -`  `         ``..-.````...``                                  :++/-``````  ` ````:+:.://.o   -``      .-`       dMMM'
echo '   :           ```                                              `/+o-./osssso:::``    ``-://+o-  `..       .-`      yMMM'
echo '   :              `.---..---....                               `:+-./oo//---.`.+s+      `/+//++-. ..       - -`     +MMM'
echo '   .         .-://////////ooo++/:.``                            -``o+/:++/+///--/+s`     `o//+/+o+oo.      `` :`    -MMM'
echo '  `` ::---:/+++/.  -//::::::///+os:.                              o+-:o-.:/-``+../+/      :o/+hs.``-        .  -`   `NMM'
echo '  .` `-++++///+/:.````.-:::-.```.-:/.                             +-`:+      `/-`-.`      .+/o+m`  `        `.` -.   hMM'
echo '  -`   ./////+:.`` `-osoo+oooo+:`  `                              +:`-::-.  -:--`-`       -+++.N+ ``         - . .-  oMM'
echo '` -`  .```-+/.````-++//::-::://oo+`                               .+-`.---:::-...-:``     +++` :. .`         . `` `-`:MM'
echo '. -. `s:--++` `  :+:--`-////::-::+o                                .+:.```.````.:/.      .o-` `oo+-   ``     .` .   .-MM'
echo ' `.. /+////`     +:.:.  .::` ./..:o-                                 .:/------:-.       `/. ` `dMN-          `` .`   `mM'
echo ' `..`://::       ```.`       -:-`--/                                   ````..`          `` `` `sMM- `        `  .```  yM'
echo '  `////-``      `+`  `-``  `::..`.--                 ``..````         `.``            `````````+Md           .  -```` +M'
echo '.-/s////-:`      :-``.`.-.---.```-:                ````.-.````````````-:////+:-..````````.`````.N/           .  :  ` `:M'
echo ':::-:-/+/+:       -/-``````````.::             `````````` `````.....``..:/+++///:-.....`..``````y`          `   o:   `.N'
echo '     .`/+++:       `-/.-...`.://.         `  ````````````` ``````````````....-.....```.``````.../           -   ym-    d'
echo '     `. .-/++`        `..--...`     `..````````````````` `````       ``````````````````` `...../``    `    -`   mNo/   y'
echo '      `.   `-/-                  `..--..````````   `   `                    `          ```````:-` `   `   ..   `osyh+` o'
echo '  ``   `.`    `              ``-///--.````````              ``                             ``--`         `-    .```/ho.s'
echo '         .`       ``  ````...:o/+/--.```````          ``.........```                        -.          .-     /.---/+/h'
echo '          ..`` `````````...------...`````          `..``       ` `.-.`                    `-.          --     -/`.+/-.`s'
echo '           .-````````````..```````` ```           --` `.-:--/-`//-.`...`                 `-`         `s-      ::/..++:.s'
echo '            `-.```....` ````````` ``            .-`.::+////::/`:/:++-``+`              `-.         `/my      -`/:::`-+od'
echo '.`            .-.......```````                 -- `++/:+/////-.`/////.:+.`           `.-`        `:hMM-     `+ :.:-:. .y'
echo ' `.`           `.:.`.````                     :-.`++:/:/::///::`-////o+/:/`        .-.``.-`    `-:NMMh      :- ` .---.`o'
echo '`  ..            `--``                       `+  .///-::/:-:/::-`:/:://:-..       .-...-.   `.-.`+MMM:      .` `.`...-.y'
echo '.`  `..`            .-`                      :+-``+:/:/::--::--:..--///:-.`.        `.-.`.-:-.```dMMm`     `.`  /``````s'
echo '`.`   `:/`            `..`                   :///:/-:/:/:--:----:`::-::::::s        .-....`  `  oMNMy      .``` /.`````s'
echo '``.`    smy:`            `..`                ::/:-.-::::/:---:-..``..:/-:` o                   :yhsd/      -````.+.....y'
echo '```-`    yMy::-``  `...`   `....``           :/://`----`````...```````.:/. /                 `+o.:/s-      -.-..```    o'
echo '.```.`   `hd-..//.-...-:-..-...---.          `/::::```````````.````````:s:`-         `      `:hNh:`:.     .:.     ` ```s'
echo '`.```.`   `+```.-/```...-`                    ////- `````  ```  ```````+/ -          ``   `--.-+mMy+.    -.`       .`  o'
echo '  ..``.`   .-`````::```                       `/ +:``````` ```````````:/...            `-::---..-sys`  `-  `        `  o'
echo '   `-....   `::-..-sd/`                        `:.:--/..````` ```````-:`-`           `/s/``...-...-:/ `-   `         ``o'
echo '     `....   `dMMMMNm/s+.          `` `          ``-``ss+//+-`````...`.`           -+s+/o/``````...-o`-    `           s'
echo '       ``..   .yhhdosdh.//-         ```          ``.---```.::`..`....           .:+:-:+/o:/. ```....:/     `           o'
echo '          ``     -yy.:yo``-+/.`                  ``   `-......` ``    `      `-o+:.-//+///:o```````./-`    `           o'
echo 'y.               sMm.`:No`./:/++:`                          ``...````      -///+//:..../:o`s.     .: `.`               o'
echo 'sy+               +s/../m..+:-.`-++//-`            ``      ``` ``       `/sos+-.s:::/:..`+`/:`   ..``.  `              s'
echo '.ymh.              -s.`.d/.//-.```:+hNNNdy/.::/:-.`.`                .+s+:-`  ``s::-:::...`-/..-:.`                    o'
echo ' /hm-/.             ./.`y:.s-..``/+hMMMMh+/--+//+ohNd/`-sso++++++++os+.         o:::/:-::` .-  `.         ``           o'
echo ' .hh../+`             :-y..y`.-`:+yMMMh:...s`:o+/::/oyossoososss/`         `    /-     .`.`.   :                      `s'